---
title: "Examples"
author: "Dave"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# See https://github.com/dsturg/PancrESS
library('edgeR')
library('Matrix.utils')
library('scRNAseq')
library('dittoSeq')
library('PancrESS')
# Install PancrESS using:
# devtools::install_github("dsturg/PancrESS",ref="master")
```

# Load data

```{r}
sce <- BaronPancreasData('human')
```

# Calculate ess

```{r}
myESS <- calcESS(sce,c("alpha", "beta","acinar","ductal"),"median","ESSDetailed")

# You can filter to include only genes at
# some maximum expression level, for example:

myESS <- subset(myESS, Max_expr >= 100)
head(myESS)

# This is an example of using the gini coefficient
# Note this returns a vector
myGini <- calcESS(sce,c("alpha", "beta","acinar","ductal"),"median","gini")
myGini[1:3]

# This is an example of using tau
# This also returns a vector
myTau <- calcESS(sce,c("alpha", "beta","acinar","ductal"),"median","tau")
myTau[1:3]


```

# Using pancreatic metadata
## Below you can load the data as a DESeqDataSet object

```{r}
library('DESeq2')
print(load("data/metapancreas_cellXstudy_DESeq.Rdata"))

myESSpan <- calcESS(metapancreas_cellXstudy_DESeq,celltypes = c("acinar","alpha","beta","delta","ductal"),aggmethod="sum",specmethod="ESSDetailed")
myESSpan <- subset(myESSpan, Max_expr >= 100)
head(myESSpan)

# Notes:
# Aggregation methods supported include "sum","mean", and "count."
# Median is preferred, so this functionality is being added

```

